name: Deploy to GitHub Pages

# This workflow is triggered on a push to the 'main' branch
on:
  push:
    branches:
      - main
  # Also allows for manual deployment
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    # Run the job on the latest Ubuntu environment
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js version 20.30
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.3.0'
      
      # Step 3: Set up Deno
      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.0.0
          
      # Step 4: Install dependencies from package.json
      - name: Install dependencies
        run: npm install
        
      # Step 5: Print Git logs for debugging
      - name: Print Git Log
        run: git log --oneline -10  # Show the last 10 commits for debug purposes

      # Step 6: Build the Astro site (output will be in the 'dist' directory)
      - name: Build Astro site
        run: |
          deno --version
          npm run astro build          

      # Step 7: Copy surveilrctl.sh and surveilrctl.ps1 to the 'dist' folder
      - name: Copy surveilrctl.sh and surveilrctl.ps1 to 'dist' folder
        run: |
          cp ./support/scripts/surveilrctl.sh ./dist/surveilrctl.sh
          cp ./support/scripts/surveilrctl.ps1 ./dist/surveilrctl.ps1

            
      # Step 8: Deploy to GitHub Pages using the 'dist' directory
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DEPLOY_TOKEN }}
          publish_dir: ./dist
           
